{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMAuthSessionTokenRefreshDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"title":"AuthSessionTokenRefreshDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate\/additionalRefreshParameters(authSession:)"]}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate":{"role":"symbol","title":"AuthSessionTokenRefreshDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"},"doc://GTMAppAuth/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate/additionalRefreshParameters(authSession:)":{"navigatorTitle":[{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}],"role":"symbol","title":"additionalRefreshParameters(authSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalRefreshParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate\/additionalRefreshParameters(authSession:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate\/additionalrefreshparameters(authsession:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GTMAuthSessionTokenRefreshDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate\/additionalRefreshParameters(authSession:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/title","value":"GTMAuthSessionTokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate~1additionalRefreshParameters(authSession:)\/title","value":"additionalRefreshParametersWithAuthSession:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate~1additionalRefreshParameters(authSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}