{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMAuthSession) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Enables you to use AppAuth with the GTM Session Fetcher library."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)NSCoding","doc:\/\/GTMAppAuth\/objc(pl)NSSecureCoding","doc:\/\/GTMAppAuth\/objc(pl)GTMFetcherAuthorizationProtocol","doc:\/\/GTMAppAuth\/objc(pl)GTMSessionFetcherAuthorizer","doc:\/\/GTMAppAuth\/objc(pl)NSObject","doc:\/\/GTMAppAuth\/s7CVarArgP","doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP","doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP","doc:\/\/GTMAppAuth\/SQ","doc:\/\/GTMAppAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"title":"AuthSession","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"AuthSession"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authState","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/canAuthorize","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/fetcherService","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/serviceProvider","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/shouldAuthorizeAllRequests","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/tokenRefreshDelegate","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmail","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailIsVerified","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userID"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:completionHandler:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:delegate:didFinish:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/encode(with:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizedRequest(_:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizingRequest(_:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/primeForRefresh()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization(for:)"]},{"title":"Type Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authStateKey","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/serviceProviderKey","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/supportsSecureCoding","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailIsVerifiedKey","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailKey","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userIDKey"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/configurationForGoogle()"]},{"title":"Enumerations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/Error"]}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)":{"role":"symbol","title":"init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serviceProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmailIsVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" using the given "},{"type":"codeVoice","code":"OIDAuthState"},{"type":"text","text":" from AppAuth."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}],"url":"\/documentation\/gtmappauth\/authsession\/init(authstate:serviceprovider:userid:useremail:useremailisverified:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/primeForRefresh()":{"role":"symbol","title":"primeForRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primeForRefresh"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not this authorization is prime for refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/primeForRefresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primeForRefresh"}],"url":"\/documentation\/gtmappauth\/authsession\/primeforrefresh()"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userEmailKey":{"role":"symbol","title":"userEmailKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmailKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailKey","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/authsession\/useremailkey"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/serviceProviderKey":{"role":"symbol","title":"serviceProviderKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceProviderKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/serviceProviderKey","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/authsession\/serviceproviderkey"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/encode(with:)":{"role":"symbol","title":"encode(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/encode(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"url":"\/documentation\/gtmappauth\/authsession\/encode(with:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userEmailIsVerified":{"role":"symbol","title":"userEmailIsVerified","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmailIsVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Email verified status; not used for authentication."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailIsVerified","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userEmailIsVerified"}],"url":"\/documentation\/gtmappauth\/authsession\/useremailisverified"},"doc://GTMAppAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/serviceProvider":{"role":"symbol","title":"serviceProvider","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Service identifier, for example “Google”; not used for authentication."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/serviceProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serviceProvider"}],"url":"\/documentation\/gtmappauth\/authsession\/serviceprovider"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/configurationForGoogle()":{"role":"symbol","title":"configurationForGoogle()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationForGoogle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OIDServiceConfiguration","preciseIdentifier":"c:objc(cs)OIDServiceConfiguration"}],"abstract":[{"type":"text","text":"Convenience method to return an @c OIDServiceConfiguration for Google."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/configurationForGoogle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configurationForGoogle"}],"url":"\/documentation\/gtmappauth\/authsession\/configurationforgoogle()"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/stopAuthorization(for:)":{"role":"symbol","title":"stopAuthorization(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Stops authorization for the provided "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" if it is queued for authorization."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAuthorizationForRequest:"}],"url":"\/documentation\/gtmappauth\/authsession\/stopauthorization(for:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/Error":{"role":"symbol","title":"AuthSession.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"Errors that may arise while authorizing a request."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/gtmappauth\/authsession\/error"},"doc://GTMAppAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/isAuthorizedRequest(_:)":{"role":"symbol","title":"isAuthorizedRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuthorizedRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the provided "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" has the “Authorization” header field."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizedRequest(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAuthorizedRequest:"}],"url":"\/documentation\/gtmappauth\/authsession\/isauthorizedrequest(_:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/authorizeRequest(_:delegate:didFinish:)":{"role":"symbol","title":"authorizeRequest(_:delegate:didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableURLRequest","preciseIdentifier":"c:objc(cs)NSMutableURLRequest"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds an authorization header to the given request, using the authorization state. Refreshes"},{"type":"text","text":" "},{"type":"text","text":"the access token if needed."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:delegate:didFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizeRequest:delegate:didFinishSelector:"}],"url":"\/documentation\/gtmappauth\/authsession\/authorizerequest(_:delegate:didfinish:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/fetcherService":{"role":"symbol","title":"fetcherService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetcherService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GTMSessionFetcherServiceProtocol","preciseIdentifier":"c:objc(pl)GTMSessionFetcherServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The fetcher service."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/fetcherService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetcherService"}],"url":"\/documentation\/gtmappauth\/authsession\/fetcherservice"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userEmail":{"role":"symbol","title":"userEmail","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user email."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userEmail"}],"url":"\/documentation\/gtmappauth\/authsession\/useremail"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/authState":{"role":"symbol","title":"authState","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"}],"abstract":[{"type":"text","text":"The AppAuth authentication state."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authState"}],"url":"\/documentation\/gtmappauth\/authsession\/authstate"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/authorizeRequest(_:completionHandler:)":{"role":"symbol","title":"authorizeRequest(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableURLRequest","preciseIdentifier":"c:objc(cs)NSMutableURLRequest"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds an authorization header to the given request, using the authorization state. Refreshes"},{"type":"text","text":" "},{"type":"text","text":"the access token if needed."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizeRequest:completionHandler:"}],"url":"\/documentation\/gtmappauth\/authsession\/authorizerequest(_:completionhandler:)"},"doc://GTMAppAuth/objc(pl)GTMSessionFetcherAuthorizer":{"type":"unresolvable","title":"GTMSessionFetcherAuthorizer","identifier":"doc:\/\/GTMAppAuth\/objc(pl)GTMSessionFetcherAuthorizer"},"doc://GTMAppAuth/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"NSSecureCoding","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSSecureCoding"},"doc://GTMAppAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/GTMAppAuth\/SQ"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/isAuthorizingRequest(_:)":{"role":"symbol","title":"isAuthorizingRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuthorizingRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the provided "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" is currently in the process of, or is in the queue"},{"type":"text","text":" "},{"type":"text","text":"for, authorization."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizingRequest(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAuthorizingRequest:"}],"url":"\/documentation\/gtmappauth\/authsession\/isauthorizingrequest(_:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userIDKey":{"role":"symbol","title":"userIDKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userIDKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userIDKey","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/authsession\/useridkey"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/authStateKey":{"role":"symbol","title":"authStateKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authStateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authStateKey","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/authsession\/authstatekey"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userEmailIsVerifiedKey":{"role":"symbol","title":"userEmailIsVerifiedKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmailIsVerifiedKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailIsVerifiedKey","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/authsession\/useremailisverifiedkey"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/shouldAuthorizeAllRequests":{"role":"symbol","title":"shouldAuthorizeAllRequests","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAuthorizeAllRequests"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"For development only, allow authorization of non-SSL requests, allowing transmission of the"},{"type":"text","text":" "},{"type":"text","text":"bearer token unencrypted."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/shouldAuthorizeAllRequests","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldAuthorizeAllRequests"}],"url":"\/documentation\/gtmappauth\/authsession\/shouldauthorizeallrequests"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/GTMAppAuth\/objc(cs)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/stopAuthorization()":{"role":"symbol","title":"stopAuthorization()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAuthorization"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops authorization for all pending requests."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAuthorization"}],"url":"\/documentation\/gtmappauth\/authsession\/stopauthorization()"},"doc://GTMAppAuth/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSCoding"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/supportsSecureCoding":{"role":"symbol","title":"supportsSecureCoding","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportsSecureCoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/supportsSecureCoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"supportsSecureCoding"}],"url":"\/documentation\/gtmappauth\/authsession\/supportssecurecoding"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/userID":{"role":"symbol","title":"userID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"User ID from the ID Token."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userID"}],"url":"\/documentation\/gtmappauth\/authsession\/userid"},"doc://GTMAppAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/GTMAppAuth\/SH"},"doc://GTMAppAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/init(authState:)":{"role":"symbol","title":"init(authState:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" using the given "},{"type":"codeVoice","code":"OIDAuthState"},{"type":"text","text":" from AppAuth."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAuthState:"}],"url":"\/documentation\/gtmappauth\/authsession\/init(authstate:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/GTMAppAuth\/s7CVarArgP"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/canAuthorize":{"role":"symbol","title":"canAuthorize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canAuthorize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the authorization state is currently valid."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/canAuthorize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canAuthorize"}],"url":"\/documentation\/gtmappauth\/authsession\/canauthorize"},"doc://GTMAppAuth/objc(pl)GTMFetcherAuthorizationProtocol":{"type":"unresolvable","title":"GTMSessionFetcherCore.GTMFetcherAuthorizationProtocol","identifier":"doc:\/\/GTMAppAuth\/objc(pl)GTMFetcherAuthorizationProtocol"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/gtmappauth\/authsession\/init(coder:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/tokenRefreshDelegate":{"role":"symbol","title":"tokenRefreshDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenRefreshDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSessionTokenRefreshDelegate","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/tokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsession\/tokenrefreshdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authState","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/canAuthorize","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/fetcherService","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/serviceProvider","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/shouldAuthorizeAllRequests","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/tokenRefreshDelegate","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmail","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userEmailIsVerified","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/userID"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:completionHandler:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authorizeRequest(_:delegate:didFinish:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/encode(with:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(coder:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizedRequest(_:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/isAuthorizingRequest(_:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/primeForRefresh()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization(for:)"]},{"title":"Type Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/supportsSecureCoding"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/configurationForGoogle()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)GTMSessionFetcherAuthorizer","doc:\/\/GTMAppAuth\/objc(pl)NSSecureCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMAuthSession"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)\/title","value":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1primeForRefresh()\/title","value":"primeForRefresh"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1primeForRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"primeForRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1encode(with:)\/title","value":"encodeWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1encode(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userEmailIsVerified\/title","value":"userEmailIsVerified"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userEmailIsVerified\/fragments","value":[{"kind":"identifier","text":"userEmailIsVerified"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1serviceProvider\/title","value":"serviceProvider"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1serviceProvider\/fragments","value":[{"kind":"identifier","text":"serviceProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1configurationForGoogle()\/title","value":"configurationForGoogle"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1configurationForGoogle()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationForGoogle"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization(for:)\/title","value":"stopAuthorizationForRequest:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAuthorizationForRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1isAuthorizedRequest(_:)\/title","value":"isAuthorizedRequest:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1isAuthorizedRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isAuthorizedRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authorizeRequest(_:delegate:didFinish:)\/title","value":"authorizeRequest:delegate:didFinishSelector:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authorizeRequest(_:delegate:didFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizeRequest:delegate:didFinishSelector:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1fetcherService\/title","value":"fetcherService"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1fetcherService\/fragments","value":[{"kind":"identifier","text":"fetcherService"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userEmail\/title","value":"userEmail"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userEmail\/fragments","value":[{"kind":"identifier","text":"userEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authState\/title","value":"authState"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authState\/fragments","value":[{"kind":"identifier","text":"authState"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authorizeRequest(_:completionHandler:)\/title","value":"authorizeRequest:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authorizeRequest(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizeRequest:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1isAuthorizingRequest(_:)\/title","value":"isAuthorizingRequest:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1isAuthorizingRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isAuthorizingRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1shouldAuthorizeAllRequests\/title","value":"shouldAuthorizeAllRequests"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1shouldAuthorizeAllRequests\/fragments","value":[{"kind":"identifier","text":"shouldAuthorizeAllRequests"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization()\/title","value":"stopAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1supportsSecureCoding\/title","value":"supportsSecureCoding"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1supportsSecureCoding\/fragments","value":[{"kind":"identifier","text":"supportsSecureCoding"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userID\/title","value":"userID"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:)\/title","value":"initWithAuthState:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthState:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1canAuthorize\/title","value":"canAuthorize"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1canAuthorize\/fragments","value":[{"kind":"identifier","text":"canAuthorize"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1tokenRefreshDelegate\/title","value":"tokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1tokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"tokenRefreshDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}