{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMAuthSessionStore) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsessionstore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsessionstore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the operations needed to provide "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" storage."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"title":"AuthSessionStore","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionStore","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"AuthSessionStore"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/removeAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/retrieveAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/save(authSession:)"]}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore/removeAuthSession()":{"navigatorTitle":[{"kind":"identifier","text":"removeAuthSessionAndReturnError:"}],"role":"symbol","title":"removeAuthSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Removes the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/removeAuthSession()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessionstore\/removeauthsession()"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore":{"role":"symbol","title":"AuthSessionStore","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"abstract":[{"type":"text","text":"Represents the operations needed to provide "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" storage."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionStore"}],"url":"\/documentation\/gtmappauth\/authsessionstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore/save(authSession:)":{"navigatorTitle":[{"kind":"identifier","text":"saveAuthSession:error:"}],"role":"symbol","title":"save(authSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"save"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Saves the provided "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/save(authSession:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessionstore\/save(authsession:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore/retrieveAuthSession()":{"navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}],"role":"symbol","title":"retrieveAuthSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Retrieves the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/retrieveAuthSession()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessionstore\/retrieveauthsession()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GTMAuthSessionStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/removeAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/retrieveAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/save(authSession:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMAuthSessionStore"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1removeAuthSession()\/title","value":"removeAuthSessionAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1removeAuthSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAuthSessionAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/title","value":"GTMAuthSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1save(authSession:)\/title","value":"saveAuthSession:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1save(authSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveAuthSession:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1retrieveAuthSession()\/title","value":"retrieveAuthSessionAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1retrieveAuthSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}