{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMKeychainStoreErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/errorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/errorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/SQ","doc:\/\/GTMAppAuth\/SH","doc:\/\/GTMAppAuth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes associated with cases from "},{"type":"codeVoice","code":"KeychainStore.Error"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@GTMAppAuth@E@GTMKeychainStoreErrorCode","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertAuthSessionToData","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertKeychainDataToAuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertRedirectURItoURL","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToCreateResponseStringFromAuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePassword","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePasswordBecauseItemNotFound","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToSetPassword","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/noService","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/passwordNotFound","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unexpectedPasswordData","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unhandled"]},{"title":"Initializers","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/Equatable-Implementations","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToDeletePassword":{"role":"symbol","title":"ErrorCode.failedToDeletePassword","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToDeletePassword"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePassword","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtodeletepassword"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtmappauth\/errorcode\/equatable-implementations"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/unhandled":{"role":"symbol","title":"ErrorCode.unhandled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhandled"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unhandled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeUnhandled"}],"url":"\/documentation\/gtmappauth\/errorcode\/unhandled"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToSetPassword":{"role":"symbol","title":"ErrorCode.failedToSetPassword","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToSetPassword"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToSetPassword","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToSetPassword"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtosetpassword"},"doc://GTMAppAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/GTMAppAuth\/SQ"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToConvertKeychainDataToAuthSession":{"role":"symbol","title":"ErrorCode.failedToConvertKeychainDataToAuthSession","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToConvertKeychainDataToAuthSession"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertKeychainDataToAuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertKeychainDataToAuthSession"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtoconvertkeychaindatatoauthsession"},"doc://GTMAppAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/GTMAppAuth\/SH"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/GTMAppAuth\/SY"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/unexpectedPasswordData":{"role":"symbol","title":"ErrorCode.unexpectedPasswordData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedPasswordData"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unexpectedPasswordData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeUnexpectedPasswordData"}],"url":"\/documentation\/gtmappauth\/errorcode\/unexpectedpassworddata"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/noService":{"role":"symbol","title":"ErrorCode.noService","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noService"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/noService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeNoService"}],"url":"\/documentation\/gtmappauth\/errorcode\/noservice"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/passwordNotFound":{"role":"symbol","title":"ErrorCode.passwordNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passwordNotFound"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/passwordNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodePasswordNotFound"}],"url":"\/documentation\/gtmappauth\/errorcode\/passwordnotfound"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/errorcode\/init(rawvalue:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToConvertRedirectURItoURL":{"role":"symbol","title":"ErrorCode.failedToConvertRedirectURItoURL","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToConvertRedirectURItoURL"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertRedirectURItoURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertRedirectURItoURL"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtoconvertredirecturitourl"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToConvertAuthSessionToData":{"role":"symbol","title":"ErrorCode.failedToConvertAuthSessionToData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToConvertAuthSessionToData"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertAuthSessionToData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertAuthSessionToData"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtoconvertauthsessiontodata"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToCreateResponseStringFromAuthSession":{"role":"symbol","title":"ErrorCode.failedToCreateResponseStringFromAuthSession","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToCreateResponseStringFromAuthSession"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToCreateResponseStringFromAuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToCreateResponseStringFromAuthSession"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtocreateresponsestringfromauthsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtmappauth\/errorcode\/rawrepresentable-implementations"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode":{"role":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"Error codes associated with cases from "},{"type":"codeVoice","code":"KeychainStore.Error"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/gtmappauth\/errorcode"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToDeletePasswordBecauseItemNotFound":{"role":"symbol","title":"ErrorCode.failedToDeletePasswordBecauseItemNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToDeletePasswordBecauseItemNotFound"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePasswordBecauseItemNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePasswordBecauseItemNotFound"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtodeletepasswordbecauseitemnotfound"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"GTMKeychainStoreErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertAuthSessionToData","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertKeychainDataToAuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToConvertRedirectURItoURL","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToCreateResponseStringFromAuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePassword","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePasswordBecauseItemNotFound","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToSetPassword","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/noService","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/passwordNotFound","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unexpectedPasswordData","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/unhandled"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMKeychainStoreErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePassword\/title","value":"GTMKeychainStoreErrorCodeFailedToDeletePassword"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePassword\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1unhandled\/title","value":"GTMKeychainStoreErrorCodeUnhandled"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1unhandled\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeUnhandled"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToSetPassword\/title","value":"GTMKeychainStoreErrorCodeFailedToSetPassword"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToSetPassword\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToSetPassword"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertKeychainDataToAuthSession\/title","value":"GTMKeychainStoreErrorCodeFailedToConvertKeychainDataToAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertKeychainDataToAuthSession\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertKeychainDataToAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1unexpectedPasswordData\/title","value":"GTMKeychainStoreErrorCodeUnexpectedPasswordData"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1unexpectedPasswordData\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeUnexpectedPasswordData"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1noService\/title","value":"GTMKeychainStoreErrorCodeNoService"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1noService\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeNoService"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1passwordNotFound\/title","value":"GTMKeychainStoreErrorCodePasswordNotFound"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1passwordNotFound\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodePasswordNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertRedirectURItoURL\/title","value":"GTMKeychainStoreErrorCodeFailedToConvertRedirectURItoURL"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertRedirectURItoURL\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertRedirectURItoURL"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertAuthSessionToData\/title","value":"GTMKeychainStoreErrorCodeFailedToConvertAuthSessionToData"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToConvertAuthSessionToData\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToConvertAuthSessionToData"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToCreateResponseStringFromAuthSession\/title","value":"GTMKeychainStoreErrorCodeFailedToCreateResponseStringFromAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToCreateResponseStringFromAuthSession\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToCreateResponseStringFromAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode\/title","value":"GTMKeychainStoreErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePasswordBecauseItemNotFound\/title","value":"GTMKeychainStoreErrorCodeFailedToDeletePasswordBecauseItemNotFound"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePasswordBecauseItemNotFound\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePasswordBecauseItemNotFound"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}