{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMOAuth2Compatibility) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The methods of this class are capable of serializing and deserializing auth objects in a way"},{"type":"text","text":" "},{"type":"text","text":"compatible with the serialization in "},{"type":"codeVoice","code":"GTMOAuth2ViewControllerTouch"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"GTMOAuth2WindowController"},{"type":"text","text":" in GTMOAuth2."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)NSObject","doc:\/\/GTMAppAuth\/s7CVarArgP","doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP","doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP","doc:\/\/GTMAppAuth\/SQ","doc:\/\/GTMAppAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Class to support serialization and deserialization of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in the format used by"},{"type":"text","text":" "},{"type":"text","text":"GTMOAuth2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"title":"GTMOAuth2Compatibility","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTMAppAuth@objc(cs)GTMOAuth2Compatibility","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/persistenceResponseString(forAuthSession:)"]}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility":{"role":"symbol","title":"GTMOAuth2Compatibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"abstract":[{"type":"text","text":"Class to support serialization and deserialization of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in the format used by"},{"type":"text","text":" "},{"type":"text","text":"GTMOAuth2."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility"},"doc://GTMAppAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/GTMAppAuth\/s7CVarArgP"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility\/init"},"doc://GTMAppAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/GTMAppAuth\/objc(cs)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)":{"role":"symbol","title":"authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPersistenceString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Creates an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from the provided persistence string."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility\/authsession(forpersistencestring:tokenurl:redirecturi:clientid:clientsecret:)"},"doc://GTMAppAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSObject"},"doc://GTMAppAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/GTMAppAuth\/SH"},"doc://GTMAppAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP"},"doc://GTMAppAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/GTMAppAuth\/SQ"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility/persistenceResponseString(forAuthSession:)":{"role":"symbol","title":"persistenceResponseString(forAuthSession:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceResponseString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAuthSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Encodes the given "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in a GTMOAuth2 compatible persistence string using URL param"},{"type":"text","text":" "},{"type":"text","text":"key\/value encoding."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/persistenceResponseString(forAuthSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility\/persistenceresponsestring(forauthsession:)"},"doc://GTMAppAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTMOAuth2Compatibility"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/persistenceResponseString(forAuthSession:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/title","value":"GTMOAuth2Compatibility"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/fragments","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)\/title","value":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1persistenceResponseString(forAuthSession:)\/title","value":"persistenceResponseStringForAuthSession:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1persistenceResponseString(forAuthSession:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}