{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMKeychainAttribute) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainattribute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/GTMAppAuth\/objc(pl)NSObject","doc:\/\/GTMAppAuth\/s7CVarArgP","doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP","doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP","doc:\/\/GTMAppAuth\/SQ","doc:\/\/GTMAppAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/init(attribute:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/attribute-swift.property"]},{"title":"Type Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/useDataProtectionKeychain"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/keychainAccessGroup(name:)"]},{"title":"Enumerations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/Attribute-swift.enum"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"title":"KeychainAttribute","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"references":{"doc://GTMAppAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/GTMAppAuth\/SH"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/keychainAccessGroup(name:)":{"role":"symbol","title":"keychainAccessGroup(name:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/keychainAccessGroup(name:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keychainAccessGroupWithName:"}],"url":"\/documentation\/gtmappauth\/keychainattribute\/keychainaccessgroup(name:)"},"doc://GTMAppAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/GTMAppAuth\/objc(cs)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/useDataProtectionKeychain":{"role":"symbol","title":"useDataProtectionKeychain","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDataProtectionKeychain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/useDataProtectionKeychain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useDataProtectionKeychain"}],"url":"\/documentation\/gtmappauth\/keychainattribute\/usedataprotectionkeychain"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/Attribute-swift.enum":{"role":"symbol","title":"KeychainAttribute.Attribute","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/Attribute-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Attribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute\/attribute-swift.enum"},"doc://GTMAppAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/GTMAppAuth\/SQ"},"doc://GTMAppAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/attribute-swift.property":{"role":"symbol","title":"attribute","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"attribute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Attribute","preciseIdentifier":"s:10GTMAppAuth17KeychainAttributeC0D0O"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/attribute-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/keychainattribute\/attribute-swift.property"},"doc://GTMAppAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSObject"},"doc://GTMAppAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/GTMAppAuth\/s7CVarArgP"},"doc://GTMAppAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/init(attribute:)":{"role":"symbol","title":"init(attribute:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attribute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Attribute","preciseIdentifier":"s:10GTMAppAuth17KeychainAttributeC0D0O"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/init(attribute:)","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/keychainattribute\/init(attribute:)"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/useDataProtectionKeychain"]},{"title":"Type Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/keychainAccessGroup(name:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMKeychainAttribute"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1keychainAccessGroup(name:)\/title","value":"keychainAccessGroupWithName:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1keychainAccessGroup(name:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"keychainAccessGroupWithName:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1useDataProtectionKeychain\/title","value":"useDataProtectionKeychain"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1useDataProtectionKeychain\/fragments","value":[{"kind":"identifier","text":"useDataProtectionKeychain"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}