{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMKeychainHelper) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainhelper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainhelper"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol defining the helper API for interacting with the Keychain."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"title":"KeychainHelper","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@GTMAppAuth@objc(pl)GTMKeychainHelper","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"KeychainHelper"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/init(keychainAttributes:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/accountName","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainAttributes"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainQuery(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/password(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/passwordData(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/removePassword(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(_:forService:accessibility:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(data:forService:accessibility:)"]}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/init(keychainAttributes:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithKeychainAttributes:"}],"role":"symbol","title":"init(keychainAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/init(keychainAttributes:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/init(keychainattributes:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/passwordData(forService:)":{"navigatorTitle":[{"kind":"identifier","text":"passwordDataForService:error:"}],"role":"symbol","title":"passwordData(forService:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"passwordData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/passwordData(forService:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/passworddata(forservice:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/accountName":{"navigatorTitle":[{"kind":"identifier","text":"accountName"}],"role":"symbol","title":"accountName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/accountName","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/accountname"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/password(forService:)":{"navigatorTitle":[{"kind":"identifier","text":"passwordForService:error:"}],"role":"symbol","title":"password(forService:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/password(forService:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/password(forservice:)"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/keychainAttributes":{"navigatorTitle":[{"kind":"identifier","text":"keychainAttributes"}],"role":"symbol","title":"keychainAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainAttributes","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/keychainattributes"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/keychainQuery(forService:)":{"navigatorTitle":[{"kind":"identifier","text":"keychainQueryForService:"}],"role":"symbol","title":"keychainQuery(forService:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainQuery(forService:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/keychainquery(forservice:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/setPassword(_:forService:accessibility:)":{"navigatorTitle":[{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}],"role":"symbol","title":"setPassword(_:forService:accessibility:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPassword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFTypeRef","preciseIdentifier":"c:@T@CFTypeRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(_:forService:accessibility:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/setpassword(_:forservice:accessibility:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper":{"role":"symbol","title":"KeychainHelper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"abstract":[{"type":"text","text":"A protocol defining the helper API for interacting with the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainHelper"}],"url":"\/documentation\/gtmappauth\/keychainhelper"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/setPassword(data:forService:accessibility:)":{"navigatorTitle":[{"kind":"identifier","text":"setPasswordWithData:forService:accessibility:error:"}],"role":"symbol","title":"setPassword(data:forService:accessibility:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPassword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFTypeRef","preciseIdentifier":"c:@T@CFTypeRef"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(data:forService:accessibility:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/setpassword(data:forservice:accessibility:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/removePassword(forService:)":{"navigatorTitle":[{"kind":"identifier","text":"removePasswordForService:error:"}],"role":"symbol","title":"removePassword(forService:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePassword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/removePassword(forService:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/removepassword(forservice:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GTMKeychainHelper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/accountName","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainAttributes"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/init(keychainAttributes:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/keychainQuery(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/password(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/passwordData(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/removePassword(forService:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(_:forService:accessibility:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(data:forService:accessibility:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMKeychainHelper"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1init(keychainAttributes:)\/title","value":"initWithKeychainAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1init(keychainAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeychainAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1passwordData(forService:)\/title","value":"passwordDataForService:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1passwordData(forService:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"passwordDataForService:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1accountName\/title","value":"accountName"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1accountName\/fragments","value":[{"kind":"identifier","text":"accountName"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1password(forService:)\/title","value":"passwordForService:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1password(forService:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"passwordForService:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1keychainAttributes\/title","value":"keychainAttributes"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1keychainAttributes\/fragments","value":[{"kind":"identifier","text":"keychainAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1keychainQuery(forService:)\/title","value":"keychainQueryForService:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1keychainQuery(forService:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"keychainQueryForService:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(_:forService:accessibility:)\/title","value":"setPassword:forService:accessibility:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(_:forService:accessibility:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/title","value":"GTMKeychainHelper"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/fragments","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(data:forService:accessibility:)\/title","value":"setPasswordWithData:forService:accessibility:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(data:forService:accessibility:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPasswordWithData:forService:accessibility:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1removePassword(forService:)\/title","value":"removePasswordForService:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1removePassword(forService:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removePasswordForService:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}