{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(GTMKeychainStore) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainstore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainstore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","doc:\/\/GTMAppAuth\/objc(pl)NSObject","doc:\/\/GTMAppAuth\/s7CVarArgP","doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP","doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP","doc:\/\/GTMAppAuth\/SQ","doc:\/\/GTMAppAuth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"title":"KeychainStore","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GTMAppAuth@objc(cs)GTMKeychainStore","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:keychainHelper:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainHelper:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/itemName","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/keychainAttributes"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession(withItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession(forItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:forItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/saveWithGTMOAuth2Format(forAuthSession:)"]},{"title":"Enumerations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error"]},{"title":"Default Implementations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/AuthSessionStore-Implementations"],"generated":true}],"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/save(authSession:forItemName:)":{"role":"symbol","title":"save(authSession:forItemName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"save"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:forItemName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"saveAuthSession:forItemName:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/save(authsession:foritemname:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/keychainAttributes":{"role":"symbol","title":"keychainAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Attributes that configure the behavior of the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/keychainAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keychainAttributes"}],"url":"\/documentation\/gtmappauth\/keychainstore\/keychainattributes"},"doc://GTMAppAuth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s23CustomStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)":{"role":"symbol","title":"retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Attempts to create an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from stored data in GTMOAuth2 format."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/retrieveauthsessioningtmoauth2format(tokenurl:redirecturi:clientid:clientsecret:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/init(itemName:keychainAttributes:)":{"role":"symbol","title":"init(itemName:keychainAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"An initializer for testing to create an instance of this keychain wrapper with a given helper."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithItemName:keychainAttributes:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/init(itemname:keychainattributes:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/init(itemName:keychainAttributes:keychainHelper:)":{"role":"symbol","title":"init(itemName:keychainAttributes:keychainHelper:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"keychainHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeychainHelper","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMKeychainHelper"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An initializer for testing to create an instance of this keychain wrapper with a given helper."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:keychainHelper:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithItemName:keychainAttributes:keychainHelper:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/init(itemname:keychainattributes:keychainhelper:)"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"},"doc://GTMAppAuth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/GTMAppAuth\/s28CustomDebugStringConvertibleP"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)":{"role":"symbol","title":"retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSessionForGoogleInGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Attempts to create a "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from data stored in a GTMOAuth2 format."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionForGoogleInGTMOAuth2FormatWithClientID:clientSecret:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/retrieveauthsessionforgoogleingtmoauth2format(clientid:clientsecret:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/Error":{"role":"symbol","title":"KeychainStore.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"Errors that may arise while saving, reading, and removing passwords from the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/gtmappauth\/keychainstore\/error"},"doc://GTMAppAuth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/GTMAppAuth\/objc(cs)NSObject"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/removeAuthSession(withItemName:)":{"role":"symbol","title":"removeAuthSession(withItemName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAuthSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withItemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession(withItemName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeAuthSessionWithItemName:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/removeauthsession(withitemname:)"},"doc://GTMAppAuth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/GTMAppAuth\/objc(pl)NSObject"},"doc://GTMAppAuth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/GTMAppAuth\/s7CVarArgP"},"doc://GTMAppAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/GTMAppAuth\/SQ"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/saveWithGTMOAuth2Format(forAuthSession:)":{"role":"symbol","title":"saveWithGTMOAuth2Format(forAuthSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveWithGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAuthSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Saves the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in a GTMOAuth2 compatible manner."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/saveWithGTMOAuth2Format(forAuthSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"saveWithGTMOAuth2FormatForAuthSession:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/savewithgtmoauth2format(forauthsession:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/init(itemName:keychainHelper:)":{"role":"symbol","title":"init(itemName:keychainHelper:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keychainHelper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeychainHelper","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMKeychainHelper"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An initializer for testing to create an instance of this keychain wrapper with a given helper."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainHelper:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithItemName:keychainHelper:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/init(itemname:keychainhelper:)"},"doc://GTMAppAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/GTMAppAuth\/SH"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/itemName":{"role":"symbol","title":"itemName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name for the item to save in, retrieve, or remove from the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/itemName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemName"}],"url":"\/documentation\/gtmappauth\/keychainstore\/itemname"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/AuthSessionStore-Implementations":{"role":"collectionGroup","title":"AuthSessionStore Implementations","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/AuthSessionStore-Implementations","kind":"article","type":"topic","url":"\/documentation\/gtmappauth\/keychainstore\/authsessionstore-implementations"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore":{"role":"symbol","title":"AuthSessionStore","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"abstract":[{"type":"text","text":"Represents the operations needed to provide "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" storage."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionStore"}],"url":"\/documentation\/gtmappauth\/authsessionstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/retrieveAuthSession(forItemName:)":{"role":"symbol","title":"retrieveAuthSession(forItemName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession(forItemName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionForItemName:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/retrieveauthsession(foritemname:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/init(itemName:)":{"role":"symbol","title":"init(itemName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An initializer for to create an instance of this keychain wrapper."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithItemName:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/init(itemname:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/itemName","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/keychainAttributes"]},{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainAttributes:keychainHelper:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/init(itemName:keychainHelper:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession(withItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession(forItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:forItemName:)","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/saveWithGTMOAuth2Format(forAuthSession:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/AuthSessionStore-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/GTMAppAuth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMKeychainStore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1save(authSession:forItemName:)\/title","value":"saveAuthSession:forItemName:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1save(authSession:forItemName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveAuthSession:forItemName:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1keychainAttributes\/title","value":"keychainAttributes"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1keychainAttributes\/fragments","value":[{"kind":"identifier","text":"keychainAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)\/title","value":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainAttributes:)\/title","value":"initWithItemName:keychainAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithItemName:keychainAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainAttributes:keychainHelper:)\/title","value":"initWithItemName:keychainAttributes:keychainHelper:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainAttributes:keychainHelper:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithItemName:keychainAttributes:keychainHelper:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)\/title","value":"retrieveAuthSessionForGoogleInGTMOAuth2FormatWithClientID:clientSecret:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionForGoogleInGTMOAuth2Format(clientID:clientSecret:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionForGoogleInGTMOAuth2FormatWithClientID:clientSecret:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1removeAuthSession(withItemName:)\/title","value":"removeAuthSessionWithItemName:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1removeAuthSession(withItemName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAuthSessionWithItemName:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1saveWithGTMOAuth2Format(forAuthSession:)\/title","value":"saveWithGTMOAuth2FormatForAuthSession:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1saveWithGTMOAuth2Format(forAuthSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveWithGTMOAuth2FormatForAuthSession:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainHelper:)\/title","value":"initWithItemName:keychainHelper:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:keychainHelper:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithItemName:keychainHelper:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1itemName\/title","value":"itemName"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1itemName\/fragments","value":[{"kind":"identifier","text":"itemName"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/title","value":"GTMAuthSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSession(forItemName:)\/title","value":"retrieveAuthSessionForItemName:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSession(forItemName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionForItemName:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:)\/title","value":"initWithItemName:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1init(itemName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithItemName:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}