{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToCreateResponseStringFromAuthSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainstore\/error\/failedtocreateresponsestringfromauthsession(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error\/failedToCreateResponseStringFromAuthSession(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToCreateResponseStringFromAuthSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":")"}],"title":"KeychainStore.Error.failedToCreateResponseStringFromAuthSession(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10GTMAppAuth13KeychainStoreC5ErrorO032failedToCreateResponseStringFromB7SessionyAeA0bL0CcAEmF","modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/Error/failedToCreateResponseStringFromAuthSession(_:)":{"role":"symbol","title":"KeychainStore.Error.failedToCreateResponseStringFromAuthSession(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToCreateResponseStringFromAuthSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error\/failedToCreateResponseStringFromAuthSession(_:)","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/keychainstore\/error\/failedtocreateresponsestringfromauthsession(_:)"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/Error":{"role":"symbol","title":"KeychainStore.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"Errors that may arise while saving, reading, and removing passwords from the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/gtmappauth\/keychainstore\/error"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}