{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any error that may arise during the retrieval."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsessionstore\/retrieveauthsession()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsessionstore\/retrieveauthsession()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/retrieveAuthSession()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieves the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}],"role":"symbol","title":"retrieveAuthSession()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionStore(im)retrieveAuthSessionAndReturnError:","required":true,"modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore":{"role":"symbol","title":"AuthSessionStore","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"abstract":[{"type":"text","text":"Represents the operations needed to provide "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" storage."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionStore"}],"url":"\/documentation\/gtmappauth\/authsessionstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore/retrieveAuthSession()":{"navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}],"role":"symbol","title":"retrieveAuthSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Retrieves the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore\/retrieveAuthSession()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessionstore\/retrieveauthsession()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"retrieveAuthSessionAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"GTMAuthSession"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/title","value":"GTMAuthSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1retrieveAuthSession()\/title","value":"retrieveAuthSessionAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore~1retrieveAuthSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}