platform :osx, '12.0'

target 'Example-macOSForPod' do
  use_frameworks!
  project 'Example-macOSForPod'
  
  # Pods for GTMAppAuth development
  pod 'GTMAppAuth', :path => '../../', :testspecs => ['unit', 'objc-api-integration']

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth', '~> 3.0'
  pod 'GTMSessionFetcher/Core', '>= 3.3', '< 6.0'
end
