platform :osx, '10.12'

target 'Example-macOSForPod' do
  use_frameworks!
  project 'Example-macOSForPod'
  
  # Pods for GTMAppAuth development
  pod 'GTMAppAuthSwift', :path => '../../'

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth', '~> 1.5'
  pod 'GTMSessionFetcher/Core', '>= 1.0', '< 3.0'
end
