target 'Example-tvOS' do
  platform :tvos, '9.0'

  # Pods for GTMAppAuth development
  pod 'GTMAppAuth', :path => '../../'

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth/Core', '~> 1.0'
end
