{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"KeychainAttribute"},{"kind":"text","text":">)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainhelper\/init(keychainattributes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainhelper\/init(keychainattributes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/init(keychainAttributes:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithKeychainAttributes:"}],"role":"symbol","title":"init(keychainAttributes:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">)"}],"symbolKind":"init","externalID":"c:@M@GTMAppAuth@objc(pl)GTMKeychainHelper(im)initWithKeychainAttributes:","required":true,"modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/init(keychainAttributes:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithKeychainAttributes:"}],"role":"symbol","title":"init(keychainAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/init(keychainAttributes:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/init(keychainattributes:)"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper":{"role":"symbol","title":"KeychainHelper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"abstract":[{"type":"text","text":"A protocol defining the helper API for interacting with the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainHelper"}],"url":"\/documentation\/gtmappauth\/keychainhelper"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[{"type":"text","text":"The Keychain attribute used to configure the way the keychain stores your items."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithKeychainAttributes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeychainAttributes:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithKeychainAttributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<GTMKeychainAttribute *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"keychainAttributes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1init(keychainAttributes:)\/title","value":"initWithKeychainAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1init(keychainAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeychainAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/title","value":"GTMKeychainHelper"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/fragments","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}