{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPassword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forService"},{"kind":"text","text":" "},{"kind":"internalParam","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFTypeRef","preciseIdentifier":"c:@T@CFTypeRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainhelper\/setpassword(_:forservice:accessibility:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainhelper\/setpassword(_:forservice:accessibility:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(_:forService:accessibility:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}],"role":"symbol","title":"setPassword(_:forService:accessibility:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPassword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFTypeRef","preciseIdentifier":"c:@T@CFTypeRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(pl)GTMKeychainHelper(im)setPassword:forService:accessibility:error:","required":true,"modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper/setPassword(_:forService:accessibility:)":{"navigatorTitle":[{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}],"role":"symbol","title":"setPassword(_:forService:accessibility:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPassword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CFTypeRef","preciseIdentifier":"c:@T@CFTypeRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper\/setPassword(_:forService:accessibility:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/keychainhelper\/setpassword(_:forservice:accessibility:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper":{"role":"symbol","title":"KeychainHelper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"abstract":[{"type":"text","text":"A protocol defining the helper API for interacting with the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainHelper"}],"url":"\/documentation\/gtmappauth\/keychainhelper"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setPassword:forService:accessibility:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPassword:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"password"},{"kind":"text","text":" "},{"kind":"identifier","text":"forService:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"service"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accessibility"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(_:forService:accessibility:)\/title","value":"setPassword:forService:accessibility:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper~1setPassword(_:forService:accessibility:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPassword:forService:accessibility:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/title","value":"GTMKeychainHelper"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/fragments","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}