{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalRefreshParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate\/additionalrefreshparameters(authsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate\/additionalrefreshparameters(authsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate\/additionalRefreshParameters(authSession:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}],"role":"symbol","title":"additionalRefreshParameters(authSession:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalRefreshParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate(im)additionalRefreshParametersWithAuthSession:","required":true,"modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate":{"role":"symbol","title":"AuthSessionTokenRefreshDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate/additionalRefreshParameters(authSession:)":{"navigatorTitle":[{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}],"role":"symbol","title":"additionalRefreshParameters(authSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalRefreshParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate\/additionalRefreshParameters(authSession:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate\/additionalrefreshparameters(authsession:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"additionalRefreshParametersWithAuthSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"GTMAuthSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authSession"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/title","value":"GTMAuthSessionTokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate~1additionalRefreshParameters(authSession:)\/title","value":"additionalRefreshParametersWithAuthSession:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate~1additionalRefreshParameters(authSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"additionalRefreshParametersWithAuthSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}