{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"KeychainAttribute"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"KeychainAttribute"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" name for the access group."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainattribute\/keychainaccessgroup(name:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainattribute\/keychainaccessgroup(name:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/keychainAccessGroup(name:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an instance of "},{"type":"codeVoice","code":"KeychainAttribute"},{"type":"text","text":" whose attribute is set to "},{"type":"codeVoice","code":".accessGroup"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"title":"keychainAccessGroup(name:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute(cm)keychainAccessGroupWithName:","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"keychainAccessGroupWithName:"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[{"type":"text","text":"The Keychain attribute used to configure the way the keychain stores your items."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/keychainAccessGroup(name:)":{"role":"symbol","title":"keychainAccessGroup(name:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"abstract":[{"type":"text","text":"Creates an instance of "},{"type":"codeVoice","code":"KeychainAttribute"},{"type":"text","text":" whose attribute is set to "},{"type":"codeVoice","code":".accessGroup"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/keychainAccessGroup(name:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keychainAccessGroupWithName:"}],"url":"\/documentation\/gtmappauth\/keychainattribute\/keychainaccessgroup(name:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"keychainAccessGroupWithName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"keychainAccessGroupWithName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"GTMKeychainAttribute"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"keychainAccessGroupWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1keychainAccessGroup(name:)\/title","value":"keychainAccessGroupWithName:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1keychainAccessGroup(name:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"keychainAccessGroupWithName:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}