{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDataProtectionKeychain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"KeychainAttribute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainattribute\/usedataprotectionkeychain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainattribute\/usedataprotectionkeychain"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/useDataProtectionKeychain","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"useDataProtectionKeychain"}],"role":"symbol","title":"useDataProtectionKeychain","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDataProtectionKeychain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"symbolKind":"property","externalID":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute(cpy)useDataProtectionKeychain","modules":[{"name":"GTMAppAuth"}],"platforms":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.15","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute/useDataProtectionKeychain":{"role":"symbol","title":"useDataProtectionKeychain","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDataProtectionKeychain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute\/useDataProtectionKeychain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useDataProtectionKeychain"}],"url":"\/documentation\/gtmappauth\/keychainattribute\/usedataprotectionkeychain"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"useDataProtectionKeychain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useDataProtectionKeychain"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"GTMKeychainAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"useDataProtectionKeychain"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1useDataProtectionKeychain\/title","value":"useDataProtectionKeychain"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute~1useDataProtectionKeychain\/fragments","value":[{"kind":"identifier","text":"useDataProtectionKeychain"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}