{"variants":[{"paths":["\/documentation\/gtmappauth\/keychainstore\/authsessionstore-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainstore\/authsessionstore-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/AuthSessionStore-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"GTMAppAuth"}],"role":"collectionGroup","title":"AuthSessionStore Implementations"},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/retrieveAuthSession()":{"role":"symbol","title":"retrieveAuthSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Retrieves the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionWithError:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/retrieveauthsession()"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/save(authSession:)":{"role":"symbol","title":"save(authSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"save"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Saves the provided "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"saveAuthSession:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/save(authsession:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/removeAuthSession()":{"role":"symbol","title":"removeAuthSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAuthSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Removes the stored "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeAuthSessionWithError:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/removeauthsession()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/removeAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSession()","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/save(authSession:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSession()\/title","value":"retrieveAuthSessionWithError:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1save(authSession:)\/title","value":"saveAuthSession:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1save(authSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveAuthSession:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1removeAuthSession()\/title","value":"removeAuthSessionWithError:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1removeAuthSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAuthSessionWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}