{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute","text":"KeychainAttribute"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainstore\/keychainattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainstore\/keychainattributes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/keychainAttributes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attributes that configure the behavior of the keychain."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">"}],"title":"keychainAttributes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTMAppAuth@objc(cs)GTMKeychainStore(py)keychainAttributes","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"keychainAttributes"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/keychainAttributes":{"role":"symbol","title":"keychainAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"KeychainAttribute","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMKeychainAttribute"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Attributes that configure the behavior of the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/keychainAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keychainAttributes"}],"url":"\/documentation\/gtmappauth\/keychainstore\/keychainattributes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"keychainAttributes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"keychainAttributes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSSet<GTMKeychainAttribute *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"keychainAttributes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1keychainAttributes\/title","value":"keychainAttributes"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1keychainAttributes\/fragments","value":[{"kind":"identifier","text":"keychainAttributes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}