{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" object."}]}]},{"kind":"parameters","parameters":[{"name":"tokenURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The OAuth token endpoint URL."}]}]},{"name":"redirectURI","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The OAuth redirect URI used when obtaining the original authorization."}]}]},{"name":"clientID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The OAuth client ID."}]}]},{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The OAuth client secret."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any error arising from the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" creation."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/keychainstore\/retrieveauthsessioningtmoauth2format(tokenurl:redirecturi:clientid:clientsecret:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/keychainstore\/retrieveauthsessioningtmoauth2format(tokenurl:redirecturi:clientid:clientsecret:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attempts to create an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from stored data in GTMOAuth2 format."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}],"role":"symbol","title":"retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"symbolKind":"method","externalID":"c:@CM@GTMAppAuth@objc(cs)GTMKeychainStore(im)retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:","extendedModule":"GTMAppAuth","modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)":{"role":"symbol","title":"retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2Format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Attempts to create an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from stored data in GTMOAuth2 format."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore\/retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}],"url":"\/documentation\/gtmappauth\/keychainstore\/retrieveauthsessioningtmoauth2format(tokenurl:redirecturi:clientid:clientsecret:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"GTMAuthSession"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tokenURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectURI:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"redirectURI"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientID"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)\/title","value":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore~1retrieveAuthSessionInGTMOAuth2Format(tokenURL:redirectURI:clientID:clientSecret:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAuthSessionInGTMOAuth2FormatWithTokenURL:redirectURI:clientID:clientSecret:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}