{"variants":[{"paths":["\/documentation\/gtmappauth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"]},{"title":"Protocols","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"GTMAppAuth","title":"GTMAppAuth","symbolKind":"module","role":"collection","modules":[{"name":"GTMAppAuth"}]},"hierarchy":{"paths":[[]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionStore":{"role":"symbol","title":"AuthSessionStore","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionStore"}],"abstract":[{"type":"text","text":"Represents the operations needed to provide "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" storage."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionStore"}],"url":"\/documentation\/gtmappauth\/authsessionstore"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate":{"role":"symbol","title":"AuthSessionTokenRefreshDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainAttribute":{"role":"symbol","title":"KeychainAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainAttribute"}],"abstract":[{"type":"text","text":"The Keychain attribute used to configure the way the keychain stores your items."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainAttribute"}],"url":"\/documentation\/gtmappauth\/keychainattribute"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMKeychainStoreErrorCode":{"role":"symbol","title":"GTMKeychainStoreErrorCode","fragments":[{"kind":"identifier","text":"GTMKeychainStoreErrorCode"}],"abstract":[{"type":"text","text":"Error codes associated with cases from "},{"type":"text","text":"KeychainStore.Error"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The cases for this enumeration are backed by integer raw values and are used to fill out the"},{"type":"text","text":" "},{"type":"text","text":"errorCode"},{"type":"text","text":" for the "},{"type":"text","text":"NSError"},{"type":"text","text":" representation of "},{"type":"text","text":"KeychainStore.Error"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMKeychainStoreErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth\/gtmkeychainstoreerrorcode"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility":{"role":"symbol","title":"GTMOAuth2Compatibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"abstract":[{"type":"text","text":"Class to support serialization and deserialization of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in the format used by"},{"type":"text","text":" "},{"type":"text","text":"GTMOAuth2."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainHelper":{"role":"symbol","title":"KeychainHelper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainHelper"}],"abstract":[{"type":"text","text":"A protocol defining the helper API for interacting with the Keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainHelper"}],"url":"\/documentation\/gtmappauth\/keychainhelper"},"doc://GTMAppAuth/documentation/GTMAppAuth/KeychainStore":{"role":"symbol","title":"KeychainStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainStore"}],"abstract":[{"type":"text","text":"A helper providing a concrete implementation for saving and loading auth data to the keychain."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainStore"}],"url":"\/documentation\/gtmappauth\/keychainstore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainAttribute","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainStore"]},{"title":"Protocols","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionStore","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/KeychainHelper"]},{"title":"Enumerations","identifiers":["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMKeychainStoreErrorCode"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/title","value":"GTMAuthSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionStore\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/title","value":"GTMAuthSessionTokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/title","value":"GTMKeychainAttribute"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainAttribute\/fragments","value":[{"kind":"identifier","text":"GTMKeychainAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/title","value":"GTMOAuth2Compatibility"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/fragments","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/title","value":"GTMKeychainHelper"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainHelper\/fragments","value":[{"kind":"identifier","text":"GTMKeychainHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/title","value":"GTMKeychainStore"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1KeychainStore\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}