{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession\/authstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession\/authstate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The AppAuth authentication state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"}],"title":"authState","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession(py)authState","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"authState"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/authState":{"role":"symbol","title":"authState","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"}],"abstract":[{"type":"text","text":"The AppAuth authentication state."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/authState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authState"}],"url":"\/documentation\/gtmappauth\/authsession\/authstate"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"authState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"authState"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":" * "},{"kind":"identifier","text":"authState"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authState\/title","value":"authState"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1authState\/fragments","value":[{"kind":"identifier","text":"authState"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}