{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationForGoogle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OIDServiceConfiguration","preciseIdentifier":"c:objc(cs)OIDServiceConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"OIDServiceConfiguration"},{"type":"text","text":" object setup with Google OAuth endpoints."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession\/configurationforgoogle()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession\/configurationforgoogle()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/configurationForGoogle()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convenience method to return an @c OIDServiceConfiguration for Google."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationForGoogle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OIDServiceConfiguration","preciseIdentifier":"c:objc(cs)OIDServiceConfiguration"}],"title":"configurationForGoogle()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession(cm)configurationForGoogle","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"configurationForGoogle"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/configurationForGoogle()":{"role":"symbol","title":"configurationForGoogle()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationForGoogle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"OIDServiceConfiguration","preciseIdentifier":"c:objc(cs)OIDServiceConfiguration"}],"abstract":[{"type":"text","text":"Convenience method to return an @c OIDServiceConfiguration for Google."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/configurationForGoogle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configurationForGoogle"}],"url":"\/documentation\/gtmappauth\/authsession\/configurationforgoogle()"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"configurationForGoogle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationForGoogle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"OIDServiceConfiguration","preciseIdentifier":"c:objc(cs)OIDServiceConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"configurationForGoogle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1configurationForGoogle()\/title","value":"configurationForGoogle"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1configurationForGoogle()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationForGoogle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}