{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serviceProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"userEmailIsVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"authState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The authorization state."}]}]},{"name":"serviceProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional string to describe the service."}]}]},{"name":"userID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional string of the user ID."}]}]},{"name":"userEmail","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional string of the user’s email address."}]}]},{"name":"userEmailIsVerified","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional string representation of a boolean to indicate"},{"type":"text","text":" "},{"type":"text","text":"that the email address has been verified. Pass “true” or “false”."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession\/init(authstate:serviceprovider:userid:useremail:useremailisverified:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession\/init(authstate:serviceprovider:userid:useremail:useremailisverified:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" using the given "},{"type":"codeVoice","code":"OIDAuthState"},{"type":"text","text":" from AppAuth."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serviceProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmailIsVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession(im)initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)":{"role":"symbol","title":"init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serviceProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmailIsVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" using the given "},{"type":"codeVoice","code":"OIDAuthState"},{"type":"text","text":" from AppAuth."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}],"url":"\/documentation\/gtmappauth\/authsession\/init(authstate:serviceprovider:userid:useremail:useremailisverified:)"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAuthState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OIDAuthState","preciseIdentifier":"c:objc(cs)OIDAuthState"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authState"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceProvider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"serviceProvider"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userID"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmail:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userEmail"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEmailIsVerified:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userEmailIsVerified"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)\/title","value":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1init(authState:serviceProvider:userID:userEmail:userEmailIsVerified:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthState:serviceProvider:userID:userEmail:userEmailIsVerified:"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}