{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession\/stopauthorization(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession\/stopauthorization(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stops authorization for the provided "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" if it is queued for authorization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":")"}],"title":"stopAuthorization(for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession(im)stopAuthorizationForRequest:","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"stopAuthorizationForRequest:"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/stopAuthorization(for:)":{"role":"symbol","title":"stopAuthorization(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Stops authorization for the provided "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" if it is queued for authorization."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/stopAuthorization(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAuthorizationForRequest:"}],"url":"\/documentation\/gtmappauth\/authsession\/stopauthorization(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopAuthorizationForRequest:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAuthorizationForRequest:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopAuthorizationForRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization(for:)\/title","value":"stopAuthorizationForRequest:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1stopAuthorization(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAuthorizationForRequest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}