{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenRefreshDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate","text":"AuthSessionTokenRefreshDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/authsession\/tokenrefreshdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/authsession\/tokenrefreshdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/tokenRefreshDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenRefreshDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSessionTokenRefreshDelegate","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate"},{"kind":"text","text":"?"}],"title":"tokenRefreshDelegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession(py)tokenRefreshDelegate","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"tokenRefreshDelegate"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSessionTokenRefreshDelegate":{"role":"symbol","title":"AuthSessionTokenRefreshDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSessionTokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSessionTokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsessiontokenrefreshdelegate"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession/tokenRefreshDelegate":{"role":"symbol","title":"tokenRefreshDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenRefreshDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSessionTokenRefreshDelegate","preciseIdentifier":"c:@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate of the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" used to supply additional parameters on token refresh."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession\/tokenRefreshDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenRefreshDelegate"}],"url":"\/documentation\/gtmappauth\/authsession\/tokenrefreshdelegate"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tokenRefreshDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tokenRefreshDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<GTMAuthSessionTokenRefreshDelegate>","preciseIdentifier":"c:Qo@M@GTMAppAuth@objc(pl)GTMAuthSessionTokenRefreshDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tokenRefreshDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/title","value":"GTMAuthSessionTokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSessionTokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"GTMAuthSessionTokenRefreshDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1tokenRefreshDelegate\/title","value":"tokenRefreshDelegate"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession~1tokenRefreshDelegate\/fragments","value":[{"kind":"identifier","text":"tokenRefreshDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}