{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToDeletePassword"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/errorcode\/failedtodeletepassword"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/errorcode\/failedtodeletepassword"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePassword","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToDeletePassword"}],"title":"ErrorCode.failedToDeletePassword","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@GTMAppAuth@E@GTMKeychainStoreErrorCode@GTMKeychainStoreErrorCodeFailedToDeletePassword","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode/failedToDeletePassword":{"role":"symbol","title":"ErrorCode.failedToDeletePassword","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToDeletePassword"}],"abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode\/failedToDeletePassword","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}],"url":"\/documentation\/gtmappauth\/errorcode\/failedtodeletepassword"},"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/ErrorCode":{"role":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"Error codes associated with cases from "},{"type":"codeVoice","code":"KeychainStore.Error"},{"type":"text","text":"."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/ErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/gtmappauth\/errorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GTMKeychainStoreErrorCodeFailedToDeletePassword"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePassword\/title","value":"GTMKeychainStoreErrorCodeFailedToDeletePassword"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode~1failedToDeletePassword\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCodeFailedToDeletePassword"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode\/title","value":"GTMKeychainStoreErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"GTMKeychainStoreErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}