platform :ios, '10.0'

target 'Example-iOSForPod' do
  use_frameworks!
  project 'Example-iOSForPod'

  # Pods for GTMAppAuth development
  pod 'GTMAppAuthSwift', :path => '../../'

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth', '~> 1.0'
  pod 'GTMSessionFetcher/Core', '>= 1.0', '< 3.0'
end
