target 'Example-iOS' do
  platform :ios, '9.0'

  # Pods for GTMAppAuth development
  pod 'GTMAppAuth', :path => '../../', :testspecs => ['Tests']

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth', '~> 1.0'
end
