{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPersistenceString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"persistenceString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" if successful."}]}]},{"kind":"parameters","parameters":[{"name":"persistenceString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" representing the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" to create."}]}]},{"name":"tokenURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" to use when creating the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}]}]},{"name":"redirectURI","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" URI to use for the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}]}]},{"name":"clientID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" client ID for the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}]}]},{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The optional "},{"type":"codeVoice","code":"String"},{"type":"text","text":" for the "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"KeychainStore.Error.failedToConvertRedirectURItoURL"},{"type":"text","text":" if "},{"type":"codeVoice","code":"redirectURI"},{"type":"text","text":" cannot be"},{"type":"text","text":" "},{"type":"text","text":"converted to a "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility\/authsession(forpersistencestring:tokenurl:redirecturi:clientid:clientsecret:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility\/authsession(forpersistencestring:tokenurl:redirecturi:clientid:clientsecret:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from the provided persistence string."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPersistenceString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"title":"authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(cs)GTMOAuth2Compatibility(im)authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility":{"role":"symbol","title":"GTMOAuth2Compatibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"abstract":[{"type":"text","text":"Class to support serialization and deserialization of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in the format used by"},{"type":"text","text":" "},{"type":"text","text":"GTMOAuth2."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)":{"role":"symbol","title":"authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPersistenceString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"redirectURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"}],"abstract":[{"type":"text","text":"Creates an "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" from the provided persistence string."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility\/authsession(forpersistencestring:tokenurl:redirecturi:clientid:clientsecret:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"GTMAuthSession"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authSessionForPersistenceString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"persistenceString"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tokenURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectURI:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"redirectURI"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientID"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/title","value":"GTMOAuth2Compatibility"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/fragments","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)\/title","value":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1authSession(forPersistenceString:tokenURL:redirectURI:clientID:clientSecret:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authSessionForPersistenceString:tokenURL:redirectURI:clientID:clientSecret:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}