{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(persistenceResponseStringForAuthSession:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceResponseString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAuthSession"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"AuthSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String?"},{"type":"text","text":" representing the GTMOAuth2 persistence representation of the"},{"type":"text","text":" "},{"type":"text","text":"authorization object."}]}]},{"kind":"parameters","parameters":[{"name":"authSession","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" to serialize in GTMOAuth2 format."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility\/persistenceresponsestring(forauthsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gtmappauth\/gtmoauth2compatibility\/persistenceresponsestring(forauthsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/persistenceResponseString(forAuthSession:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Encodes the given "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in a GTMOAuth2 compatible persistence string using URL param"},{"type":"text","text":" "},{"type":"text","text":"key\/value encoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceResponseString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAuthSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"persistenceResponseString(forAuthSession:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@GTMAppAuth@objc(cs)GTMOAuth2Compatibility(cm)persistenceResponseStringForAuthSession:","modules":[{"name":"GTMAppAuth"}],"navigatorTitle":[{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}]},"hierarchy":{"paths":[["doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility"]]},"references":{"doc://GTMAppAuth/documentation/GTMAppAuth":{"role":"collection","title":"GTMAppAuth","abstract":[],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth","kind":"symbol","type":"topic","url":"\/documentation\/gtmappauth"},"doc://GTMAppAuth/documentation/GTMAppAuth/AuthSession":{"role":"symbol","title":"AuthSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthSession"}],"abstract":[{"type":"text","text":"An implementation of the "},{"type":"codeVoice","code":"GTMFetcherAuthorizationProtocol"},{"type":"text","text":" protocol for the AppAuth library."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthSession"}],"url":"\/documentation\/gtmappauth\/authsession"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility":{"role":"symbol","title":"GTMOAuth2Compatibility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"abstract":[{"type":"text","text":"Class to support serialization and deserialization of "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in the format used by"},{"type":"text","text":" "},{"type":"text","text":"GTMOAuth2."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility"},"doc://GTMAppAuth/documentation/GTMAppAuth/GTMOAuth2Compatibility/persistenceResponseString(forAuthSession:)":{"role":"symbol","title":"persistenceResponseString(forAuthSession:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceResponseString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAuthSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Encodes the given "},{"type":"codeVoice","code":"AuthSession"},{"type":"text","text":" in a GTMOAuth2 compatible persistence string using URL param"},{"type":"text","text":" "},{"type":"text","text":"key\/value encoding."}],"identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/GTMOAuth2Compatibility\/persistenceResponseString(forAuthSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}],"url":"\/documentation\/gtmappauth\/gtmoauth2compatibility\/persistenceresponsestring(forauthsession:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"persistenceResponseStringForAuthSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/GTMAppAuth\/documentation\/GTMAppAuth\/AuthSession","preciseIdentifier":"c:@M@GTMAppAuth@objc(cs)GTMAuthSession","text":"GTMAuthSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authSession"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/title","value":"GTMAuthSession"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1AuthSession\/fragments","value":[{"kind":"identifier","text":"GTMAuthSession"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/title","value":"GTMOAuth2Compatibility"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility\/fragments","value":[{"kind":"identifier","text":"GTMOAuth2Compatibility"}]},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1persistenceResponseString(forAuthSession:)\/title","value":"persistenceResponseStringForAuthSession:"},{"op":"replace","path":"\/references\/doc:~1~1GTMAppAuth~1documentation~1GTMAppAuth~1GTMOAuth2Compatibility~1persistenceResponseString(forAuthSession:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"persistenceResponseStringForAuthSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}